# permissions for end users to edit azureapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: azureapp-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator
    app.kubernetes.io/part-of: operator
    app.kubernetes.io/managed-by: kustomize
  name: azureapp-editor-role
rules:
- apiGroups:
  - k8sapp.rda.dev
  resources:
  - azureapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8sapp.rda.dev
  resources:
  - azureapps/status
  verbs:
  - get
