---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k8sapp.rda.dev
  resources:
  - azureapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k8sapp.rda.dev
  resources:
  - azureapps/finalizers
  verbs:
  - update
- apiGroups:
  - k8sapp.rda.dev
  resources:
  - azureapps/status
  verbs:
  - get
  - patch
  - update
