apiVersion: k8sapp.rdalbuquerque.dev/v0alpha1
kind: AzureApp
metadata:
  name: app5
spec:
  identifier: apprda5
  identifierUri: api://myappuri5
  url: myapp5.local.dev
  containerImage: nginx
  servingPort: 8080
  enableDatabase: true
